// scripts/build-connections-grids.ts — bake the Connections daily grids.
//
//   node --max-old-space-size=12288 scripts/build-connections-grids.ts
//   (npm run build:connections-grids)
//
// WHY BAKE. The Connections dealer (src/lib/connections.ts dealGrid) is an
// AUTHOR-TIME engine: to deal even one grid it first enumerates the entire
// unambiguous key-quadruple space (~9.5M viable sets at the 237-film pool), which
// needs ~12 GB of heap and several seconds — it OOMs a browser tab outright. So
// the runtime never runs the dealer. Instead this script runs it once, here, over
// the SAME 365-day anchor window that sim/connections-verify.ts pins, and writes
// the grids to src/data/connections-grids.json. The mode reads today's grid from
// that file by calendar offset (src/lib/connections.ts dailyConnectionsGrid).
//
// PARITY. The baked grids ARE dealGrid's output — verify re-deals the window with
// dealGrid and pins the exact same grids, and it also asserts
// dailyConnectionsGrid(seed) === dealGrid(seed) across the window, so the baked
// file can never silently drift from the dealer. Re-run this whenever the pool
// changes (the same trigger that re-runs verify and, if a published grid moved,
// bumps the pin). Author-time only; not in the app tsconfig — Node type-strips it.

import { writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { MOVIES } from '../src/data/movies.ts'
import { localDateSeed } from '../src/lib/daily.ts'
import { dealGrid } from '../src/lib/connections.ts'

// The window MUST match sim/connections-verify.ts exactly (same ANCHOR, same
// DAYS, same localDateSeed construction) so the pinned grids and the baked grids
// are the same 365 grids. ANCHOR.m is 0-based: 6 = July. Dealer-birth date.
const ANCHOR = { y: 2026, m: 6, d: 6 }
const DAYS = 365

const OUT_PATH = 'src/data/connections-grids.json'

function main(): void {
  const seeds: string[] = []
  for (let i = 0; i < DAYS; i++) seeds.push(localDateSeed(new Date(ANCHOR.y, ANCHOR.m, ANCHOR.d + i)))

  const t0 = Date.now()
  const grids = seeds.map((s) => dealGrid(s))
  const took = ((Date.now() - t0) / 1000).toFixed(1)

  // Compact, stable JSON: anchor seed + the grids in seed order. The runtime keys
  // by offset from `anchor`, so the array order is the contract — never re-sort.
  const out = {
    _comment: 'AUTO-GENERATED by scripts/build-connections-grids.ts — do not edit by hand. Re-run on any pool change (npm run build:connections-grids), then re-run verify:connections.',
    anchor: seeds[0],
    days: DAYS,
    pool: MOVIES.length,
    grids,
  }
  writeFileSync(OUT_PATH, JSON.stringify(out, null, 0) + '\n')

  // Category-mix histogram so an unexpectedly genre-heavy bake is visible at a
  // glance (the dealer lock caps genre at 1/grid; this shows the spread).
  const mix = new Map<string, number>()
  for (const g of grids) {
    const key = g.groups.map((gr) => gr.cat[0]).sort().join('')
    mix.set(key, (mix.get(key) ?? 0) + 1)
  }
  console.log(`wrote ${grids.length} grids to ${OUT_PATH} (pool ${MOVIES.length}, ${took}s)`)
  console.log('  anchor: ' + seeds[0] + ' → ' + seeds[DAYS - 1])
  console.log('  category mixes: ' + [...mix.entries()].sort((a, b) => b[1] - a[1]).map(([k, n]) => `${k}×${n}`).join('  '))
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    main()
  } catch (err) {
    console.error((err as Error).message)
    process.exit(1)
  }
}
