// Review-only relation scaffolds for the Checkpoint-1 outside-challenger lane.
//
// IMPORTANT: these are provisional authoring records, not approved Movie data.
// They exist only so the picker can show conservative person-link projections.
// A selected challenger must still be copied into scripts/daily-duel-candidate.ts,
// checked through the tmdb-check/name/date workflow, arbitrated by Buri, and
// explicitly approved before any runtime source edit.

import type { Movie } from '../src/data/types.ts'

export interface PoolChallenger {
  movie: Movie
  sourceKind: 'dated-stub' | 'entirely-new'
  priorStatus: string
  recognizability: 'canonical' | 'high' | 'broad' | 'cult-high'
  breadthReasons: string[]
  concentrationCaveat?: string
  packageId?: string
  seriesReview?: string
  metadataStatus: 'provisional-unverified'
  identityNote: string
}

const provisional = (
  movie: Movie,
  details: Omit<PoolChallenger, 'movie' | 'metadataStatus'>,
): PoolChallenger => ({ movie, metadataStatus: 'provisional-unverified', ...details })

export const DAILY_DUEL_POOL_CHALLENGERS: PoolChallenger[] = [
  provisional(
    {
      id: 'a-quiet-place-part-ii',
      title: 'A Quiet Place Part II',
      year: 2021,
      director: ['John Krasinski'],
      writers: ['John Krasinski'],
      topCast: ['Emily Blunt', 'Cillian Murphy', 'Millicent Simmonds', 'Noah Jupe', 'Djimon Hounsou'],
      deepCast: ['John Krasinski'],
      posterColor: '#331025',
      genre: 'Horror',
      series: 'a-quiet-place',
      releaseDate: '2021-05-28',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'pre-existing Chronology stub; not selected as a full card in Wave 3',
      recognizability: 'high',
      breadthReasons: ['modern Horror', 'Emily Blunt / Cillian Murphy bridge', 'coherent sequel lane'],
      packageId: 'quiet-place-continuity',
      seriesReview: 'Would also require an explicit series ruling for existing A Quiet Place; no series-only edge is counted here.',
      identityNote: '2021 sequel, not the 2018 A Quiet Place.',
    },
  ),
  provisional(
    {
      id: 'harry-potter-and-the-deathly-hallows-part-2',
      title: 'Harry Potter and the Deathly Hallows – Part 2',
      year: 2011,
      director: ['David Yates'],
      writers: ['Steve Kloves'],
      topCast: ['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson', 'Ralph Fiennes', 'Alan Rickman'],
      deepCast: ['Helena Bonham Carter', 'Gary Oldman', 'Maggie Smith', 'Robbie Coltrane'],
      posterColor: '#43682e',
      genre: 'Adventure',
      series: 'harry-potter',
      releaseDate: '2011-07-15',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'high',
      breadthReasons: ['Harry Potter continuity', '2010s tentpole', 'strong ensemble bridge'],
      concentrationCaveat: 'Feeds an already coherent four-card Harry Potter lane.',
      seriesReview: 'Uses the existing harry-potter continuity tag.',
      identityNote: '2011 Part 2; retain the ruled en-dash title convention.',
    },
  ),
  provisional(
    {
      id: 'speed',
      title: 'Speed',
      year: 1994,
      director: ['Jan de Bont'],
      writers: ['Graham Yost'],
      topCast: ['Keanu Reeves', 'Dennis Hopper', 'Sandra Bullock', 'Joe Morton', 'Jeff Daniels'],
      posterColor: '#26303c',
      genre: 'Action',
      releaseDate: '1994-06-09',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'canonical',
      breadthReasons: ['1990s Action anchor', 'Sandra Bullock / Keanu Reeves bridge', 'non-franchise favorite'],
      identityNote: '1994 Jan de Bont film.',
    },
  ),
  provisional(
    {
      id: 'die-hard',
      title: 'Die Hard',
      year: 1988,
      director: ['John McTiernan'],
      writers: ['Jeb Stuart', 'Steven E. de Souza'],
      topCast: ['Bruce Willis', 'Alan Rickman', 'Alexander Godunov', 'Bonnie Bedelia', 'Reginald VelJohnson'],
      deepCast: ['William Atherton'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'die-hard',
      releaseDate: '1988-07-15',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Wave 3 H-lane SKIPPED; earlier Chronology stub retained',
      recognizability: 'canonical',
      breadthReasons: ['1980s Action canon', 'Bruce Willis bridge', 'holiday/action identity'],
      seriesReview: 'Single selected member would carry no series value.',
      identityNote: '1988 original.',
    },
  ),
  provisional(
    {
      id: 'ghostbusters',
      title: 'Ghostbusters',
      year: 1984,
      director: ['Ivan Reitman'],
      writers: ['Dan Aykroyd', 'Harold Ramis'],
      topCast: ['Bill Murray', 'Dan Aykroyd', 'Sigourney Weaver', 'Harold Ramis', 'Rick Moranis'],
      deepCast: ['Ernie Hudson', 'Annie Potts', 'William Atherton'],
      posterColor: '#257068',
      genre: 'Comedy',
      series: 'ghostbusters',
      releaseDate: '1984-06-08',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Wave 3 H-lane SKIPPED; earlier Chronology stub retained',
      recognizability: 'canonical',
      breadthReasons: ['1980s Comedy anchor', 'ensemble bridge', 'Comedy / supernatural lane'],
      seriesReview: 'Ghostbusters II remains a stub; no series-only edge is counted.',
      identityNote: '1984 original; must not prefix-collide with Ghostbusters II or Ghost.',
    },
  ),
  provisional(
    {
      id: 'top-gun-maverick',
      title: 'Top Gun: Maverick',
      year: 2022,
      director: ['Joseph Kosinski'],
      writers: ['Ehren Kruger', 'Eric Warren Singer', 'Christopher McQuarrie'],
      topCast: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm', 'Glen Powell'],
      deepCast: ['Ed Harris', 'Val Kilmer'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'top-gun',
      releaseDate: '2022-05-27',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Wave 3 H-lane SKIPPED; earlier Chronology stub retained',
      recognizability: 'canonical',
      breadthReasons: ['major modern favorite', 'legacy sequel bridge', 'Joseph Kosinski creator lane'],
      concentrationCaveat: 'Adds another Tom Cruise Action/franchise card.',
      packageId: 'top-gun-continuity',
      seriesReview: 'Would require an explicit series ruling for existing Top Gun.',
      identityNote: '2022 sequel.',
    },
  ),
  provisional(
    {
      id: 'john-wick',
      title: 'John Wick',
      year: 2014,
      director: ['Chad Stahelski'],
      writers: ['Derek Kolstad'],
      topCast: ['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen', 'Adrianne Palicki', 'Bridget Moynahan'],
      deepCast: ['Willem Dafoe', 'Ian McShane', 'John Leguizamo', 'Lance Reddick'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'john-wick',
      releaseDate: '2014-10-24',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'canonical',
      breadthReasons: ['modern Action anchor', 'Keanu Reeves bridge', 'coherent contemporary franchise'],
      concentrationCaveat: 'Reinforces Keanu Reeves and Action.',
      packageId: 'john-wick-pair',
      seriesReview: 'Package creates a two-card continuity; each member must pass independently.',
      identityNote: '2014 first film.',
    },
  ),
  provisional(
    {
      id: 'john-wick-chapter-4',
      title: 'John Wick: Chapter 4',
      year: 2023,
      director: ['Chad Stahelski'],
      writers: ['Shay Hatten', 'Michael Finch'],
      topCast: ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård', 'Laurence Fishburne', 'Hiroyuki Sanada'],
      deepCast: ['Ian McShane', 'Lance Reddick'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'john-wick',
      releaseDate: '2023-03-24',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'pre-existing Chronology stub; not selected as a full card in Wave 3',
      recognizability: 'high',
      breadthReasons: ['2020s Action', 'international ensemble bridge', 'coherent contemporary franchise'],
      concentrationCaveat: 'Reinforces Keanu Reeves and Action.',
      packageId: 'john-wick-pair',
      seriesReview: 'Package creates a two-card continuity; each member must pass independently.',
      identityNote: '2023 fourth film.',
    },
  ),
  provisional(
    {
      id: 'mission-impossible-dead-reckoning-part-one',
      title: 'Mission: Impossible — Dead Reckoning Part One',
      year: 2023,
      director: ['Christopher McQuarrie'],
      writers: ['Christopher McQuarrie', 'Erik Jendresen'],
      topCast: ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 'Simon Pegg', 'Rebecca Ferguson'],
      deepCast: ['Vanessa Kirby', 'Esai Morales'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'mission-impossible',
      releaseDate: '2023-07-10',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'high',
      breadthReasons: ['2020s tentpole', 'Rebecca Ferguson / Hayley Atwell bridge', 'continuity value'],
      concentrationCaveat: 'Feeds the already dominant Tom Cruise / Mission: Impossible lane.',
      seriesReview: 'Uses the existing mission-impossible continuity tag.',
      identityNote: '2023 Part One with the ruled em-dash title.',
    },
  ),
  provisional(
    {
      id: 'avengers-infinity-war',
      title: 'Avengers: Infinity War',
      year: 2018,
      director: ['Anthony Russo', 'Joe Russo'],
      writers: ['Christopher Markus', 'Stephen McFeely'],
      topCast: ['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'Chris Evans', 'Scarlett Johansson'],
      deepCast: ['Benedict Cumberbatch', 'Tom Holland', 'Chadwick Boseman', 'Josh Brolin', 'Zoe Saldaña'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'avengers',
      releaseDate: '2018-04-27',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'canonical',
      breadthReasons: ['major 2010s popular anchor', 'large cross-pool ensemble bridge', 'paired-event continuity'],
      concentrationCaveat: 'Dense superhero/ensemble card; breadth case must beat concentration.',
      packageId: 'avengers-pair',
      seriesReview: 'Package proposes avengers; whether existing The Avengers joins that continuity is a separate ruling.',
      identityNote: '2018 MCU film.',
    },
  ),
  provisional(
    {
      id: 'avengers-endgame',
      title: 'Avengers: Endgame',
      year: 2019,
      director: ['Anthony Russo', 'Joe Russo'],
      writers: ['Christopher Markus', 'Stephen McFeely'],
      topCast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson'],
      deepCast: ['Jeremy Renner', 'Don Cheadle', 'Paul Rudd', 'Brie Larson', 'Karen Gillan'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'avengers',
      releaseDate: '2019-04-26',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'canonical',
      breadthReasons: ['major 2010s popular anchor', 'large cross-pool ensemble bridge', 'paired-event continuity'],
      concentrationCaveat: 'Dense superhero/ensemble card; breadth case must beat concentration.',
      packageId: 'avengers-pair',
      seriesReview: 'Package proposes avengers; whether existing The Avengers joins that continuity is a separate ruling.',
      identityNote: '2019 MCU film; ignore later re-release entries.',
    },
  ),
  provisional(
    {
      id: 'guardians-of-the-galaxy',
      title: 'Guardians of the Galaxy',
      year: 2014,
      director: ['James Gunn'],
      writers: ['James Gunn', 'Nicole Perlman'],
      topCast: ['Chris Pratt', 'Zoe Saldaña', 'Dave Bautista', 'Vin Diesel', 'Bradley Cooper'],
      deepCast: ['Lee Pace', 'Michael Rooker', 'Karen Gillan', 'Djimon Hounsou'],
      posterColor: '#28336e',
      genre: 'Sci-Fi',
      series: 'guardians-of-the-galaxy',
      releaseDate: '2014-08-01',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'high',
      breadthReasons: ['comic Sci-Fi tone', 'James Gunn creator lane', 'ensemble bridge'],
      concentrationCaveat: 'Still adds superhero/franchise density.',
      packageId: 'guardians-pair',
      seriesReview: 'Package creates a two-card continuity; each member must pass independently.',
      identityNote: '2014 first film.',
    },
  ),
  provisional(
    {
      id: 'guardians-of-the-galaxy-vol-3',
      title: 'Guardians of the Galaxy Vol. 3',
      year: 2023,
      director: ['James Gunn'],
      writers: ['James Gunn'],
      topCast: ['Chris Pratt', 'Zoe Saldaña', 'Dave Bautista', 'Karen Gillan', 'Pom Klementieff'],
      deepCast: ['Vin Diesel', 'Bradley Cooper', 'Will Poulter', 'Chukwudi Iwuji', 'Sylvester Stallone'],
      posterColor: '#28336e',
      genre: 'Sci-Fi',
      series: 'guardians-of-the-galaxy',
      releaseDate: '2023-05-05',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'high',
      breadthReasons: ['2020s popular anchor', 'James Gunn creator lane', 'ensemble bridge'],
      concentrationCaveat: 'Still adds superhero/franchise density.',
      packageId: 'guardians-pair',
      seriesReview: 'Package creates a two-card continuity; each member must pass independently.',
      identityNote: '2023 third film.',
    },
  ),
  provisional(
    {
      id: 'spider-man-no-way-home',
      title: 'Spider-Man: No Way Home',
      year: 2021,
      director: ['Jon Watts'],
      writers: ['Chris McKenna', 'Erik Sommers'],
      topCast: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Jacob Batalon', 'Jon Favreau'],
      deepCast: ['Willem Dafoe', 'Alfred Molina', 'Jamie Foxx', 'Andrew Garfield', 'Tobey Maguire'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'spider-man-holland',
      releaseDate: '2021-12-17',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'pre-existing Chronology stub; not selected as a full card in Wave 3',
      recognizability: 'canonical',
      breadthReasons: ['major 2020s popular anchor', 'multi-era Spider-Man bridge', 'Tom Holland continuity'],
      concentrationCaveat: 'Adds another superhero/franchise card.',
      seriesReview: 'Uses the same Holland-continuity tag as Spider-Man: Brand New Day; not the Raimi Spider-Man card.',
      identityNote: '2021 Holland-continuity film.',
    },
  ),
  provisional(
    {
      id: 'everything-everywhere-all-at-once',
      title: 'Everything Everywhere All at Once',
      year: 2022,
      director: ['Daniel Kwan', 'Daniel Scheinert'],
      writers: ['Daniel Kwan', 'Daniel Scheinert'],
      topCast: ['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan', 'Jamie Lee Curtis', 'James Hong'],
      posterColor: '#28336e',
      genre: 'Sci-Fi',
      releaseDate: '2022-03-25',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'pre-existing Chronology stub; not selected as a full card in Wave 3',
      recognizability: 'high',
      breadthReasons: ['2020s original Sci-Fi', 'Daniels creator lane', 'Michelle Yeoh bridge'],
      identityNote: '2022 Daniels film.',
    },
  ),
  provisional(
    {
      id: 'hidden-figures',
      title: 'Hidden Figures',
      year: 2016,
      director: ['Theodore Melfi'],
      writers: ['Allison Schroeder', 'Theodore Melfi'],
      topCast: ['Taraji P. Henson', 'Octavia Spencer', 'Janelle Monáe', 'Kevin Costner', 'Kirsten Dunst'],
      deepCast: ['Mahershala Ali', 'Glen Powell', 'Jim Parsons'],
      posterColor: '#66461f',
      genre: 'Drama',
      releaseDate: '2016-12-10',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'high',
      breadthReasons: ['women-led historical Drama', 'Black ensemble anchor', '2010s non-franchise breadth'],
      identityNote: '2016 Theodore Melfi film.',
    },
  ),
  provisional(
    {
      id: 'thelma-and-louise',
      title: 'Thelma & Louise',
      year: 1991,
      director: ['Ridley Scott'],
      writers: ['Callie Khouri'],
      topCast: ['Susan Sarandon', 'Geena Davis', 'Harvey Keitel', 'Michael Madsen', 'Brad Pitt'],
      deepCast: ['Christopher McDonald'],
      posterColor: '#66461f',
      genre: 'Drama',
      releaseDate: '1991-05-24',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Stage B KEEP for Chronology; not selected as a full card in Wave 3',
      recognizability: 'canonical',
      breadthReasons: ['women-led 1990s road film', 'Callie Khouri writer lane', 'Ridley Scott / Brad Pitt bridge'],
      identityNote: '1991 Ridley Scott film.',
    },
  ),
  provisional(
    {
      id: 'clueless',
      title: 'Clueless',
      year: 1995,
      director: ['Amy Heckerling'],
      writers: ['Amy Heckerling'],
      topCast: ['Alicia Silverstone', 'Stacey Dash', 'Brittany Murphy', 'Paul Rudd', 'Donald Faison'],
      deepCast: ['Breckin Meyer', 'Jeremy Sisto'],
      posterColor: '#257068',
      genre: 'Comedy',
    },
    {
      sourceKind: 'entirely-new',
      priorStatus: 'Wave 3 H-lane SKIPPED; no local dated stub',
      recognizability: 'canonical',
      breadthReasons: ['women-directed 1990s Comedy', 'teen-film anchor', 'Paul Rudd / Donald Faison bridge'],
      identityNote: '1995 Amy Heckerling film.',
    },
  ),
  provisional(
    {
      id: 'legally-blonde',
      title: 'Legally Blonde',
      year: 2001,
      director: ['Robert Luketic'],
      writers: ['Karen McCullah Lutz', 'Kirsten Smith'],
      topCast: ['Reese Witherspoon', 'Luke Wilson', 'Selma Blair', 'Matthew Davis', 'Victor Garber'],
      deepCast: ['Jennifer Coolidge', 'Holland Taylor'],
      posterColor: '#257068',
      genre: 'Comedy',
    },
    {
      sourceKind: 'entirely-new',
      priorStatus: 'Wave 3 H-lane SKIPPED; no local dated stub',
      recognizability: 'canonical',
      breadthReasons: ['women-led 2000s Comedy', 'Reese Witherspoon anchor', 'rom-com / campus breadth'],
      identityNote: '2001 original; writer-name convention requires audit.',
    },
  ),
  provisional(
    {
      id: 'mean-girls-2004',
      title: 'Mean Girls (2004)',
      year: 2004,
      director: ['Mark Waters'],
      writers: ['Tina Fey'],
      topCast: ['Lindsay Lohan', 'Rachel McAdams', 'Lacey Chabert', 'Amanda Seyfried', 'Lizzy Caplan'],
      deepCast: ['Tina Fey', 'Tim Meadows', 'Amy Poehler'],
      posterColor: '#257068',
      genre: 'Comedy',
    },
    {
      sourceKind: 'entirely-new',
      priorStatus: 'Wave 3 H-lane SKIPPED; no local dated stub',
      recognizability: 'canonical',
      breadthReasons: ['women-written 2000s Comedy', 'teen-film anchor', 'Rachel McAdams / Tina Fey bridge'],
      identityNote: '2004 original, explicitly disambiguated from the 2024 film.',
    },
  ),
  provisional(
    {
      id: 'the-breakfast-club',
      title: 'The Breakfast Club',
      year: 1985,
      director: ['John Hughes'],
      writers: ['John Hughes'],
      topCast: ['Emilio Estevez', 'Molly Ringwald', 'Judd Nelson', 'Anthony Michael Hall', 'Ally Sheedy'],
      deepCast: ['Paul Gleason', 'John Kapelos'],
      posterColor: '#257068',
      genre: 'Comedy',
      releaseDate: '1985-02-15',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Wave 3 H-lane SKIPPED; earlier Chronology stub retained',
      recognizability: 'canonical',
      breadthReasons: ['1980s teen-film anchor', 'John Hughes creator lane', 'ensemble Comedy breadth'],
      identityNote: '1985 John Hughes film.',
    },
  ),
  provisional(
    {
      id: 'the-batman',
      title: 'The Batman',
      year: 2022,
      director: ['Matt Reeves'],
      writers: ['Matt Reeves', 'Peter Craig'],
      topCast: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Jeffrey Wright', 'Colin Farrell'],
      deepCast: ['John Turturro', 'Andy Serkis'],
      posterColor: '#26303c',
      genre: 'Action',
      series: 'the-batman',
      releaseDate: '2022-03-04',
    },
    {
      sourceKind: 'dated-stub',
      priorStatus: 'Wave 3 H-lane SKIPPED; earlier Chronology stub retained',
      recognizability: 'high',
      breadthReasons: ['2020s popular anchor', 'Matt Reeves creator lane', 'Pattinson / Dano / Farrell bridge'],
      concentrationCaveat: 'Adds Batman/superhero density despite a separate continuity.',
      seriesReview: 'Must remain separate from Nolan dark-knight and 1989 Batman continuities.',
      identityNote: '2022 Matt Reeves continuity.',
    },
  ),
]
