// scripts/wave3-candidate.ts — REVIEW-ONLY selected Wave 3 draft.
// Generated from Buri's 2026-08-08 A+B+C01-C17+E+F selection.
// TMDB is author-time evidence, not the judge. Do not merge until audits and rulings complete.
import type { Movie } from '../src/data/types.ts'

export const MOVIES: Movie[] = [
  // A01 — selected by Buri 2026-08-08; TMDB 13223 scaffold, review-only
  {
    id: 'gran-torino',
    title: 'Gran Torino',
    year: 2008,
    director: ['Clint Eastwood'],
    writers: ['Nick Schenk'],
    topCast: ['Clint Eastwood', 'Christopher Carley', 'Bee Vang', 'Ahney Her', 'Brian Haley'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '2008-12-12',
  },
  // A02 — selected by Buri 2026-08-08; TMDB 856 scaffold, review-only
  {
    id: 'who-framed-roger-rabbit',
    title: 'Who Framed Roger Rabbit',
    year: 1988,
    director: ['Robert Zemeckis'],
    writers: ['Peter S. Seaman', 'Jeffrey Price'],
    topCast: ['Bob Hoskins', 'Christopher Lloyd', 'Joanna Cassidy', 'Charles Fleischer', 'Kathleen Turner'],
    posterColor: '#2d70b6',
    genre: 'Animation',
    releaseDate: '1988-06-22',
  },
  // A03 — selected by Buri 2026-08-08; TMDB 10386 scaffold, review-only
  {
    id: 'the-iron-giant',
    title: 'The Iron Giant',
    year: 1999,
    director: ['Brad Bird'],
    writers: ['Tim McCanlies'],
    topCast: ['Vin Diesel', 'Eli Marienthal', 'Jennifer Aniston', 'Harry Connick Jr.', 'Christopher McDonald'],
    posterColor: '#2d70b6',
    genre: 'Animation',
    releaseDate: '1999-08-06',
  },
  // A04 — selected by Buri 2026-08-08; TMDB 661374 scaffold, review-only
  {
    id: 'glass-onion-a-knives-out-mystery',
    title: 'Glass Onion: A Knives Out Mystery',
    year: 2022,
    director: ['Rian Johnson'],
    writers: ['Rian Johnson'],
    topCast: ['Daniel Craig', 'Edward Norton', 'Janelle Monáe', 'Kathryn Hahn', 'Leslie Odom Jr.'],
    deepCast: ['Dave Bautista', 'Jessica Henwick', 'Ethan Hawke', 'Hugh Grant', 'Joseph Gordon-Levitt'],
    posterColor: '#4a3960',
    genre: 'Thriller',
    series: 'knives-out',
    releaseDate: '2022-11-23',
  },
  // A05 — selected by Buri 2026-08-08; TMDB 9802 scaffold, review-only
  {
    id: 'the-rock',
    title: 'The Rock',
    year: 1996,
    director: ['Michael Bay'],
    writers: ['David Weisberg', 'Douglas S. Cook', 'Mark Rosner'],
    topCast: ['Sean Connery', 'Nicolas Cage', 'Ed Harris', 'John Spencer', 'David Morse'],
    deepCast: ['Michael Biehn'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '1996-06-07',
  },
  // A06 — selected by Buri 2026-08-08; TMDB 264660 scaffold, review-only
  {
    id: 'ex-machina',
    title: 'Ex Machina',
    year: 2015,
    director: ['Alex Garland'],
    writers: ['Alex Garland'],
    topCast: ['Domhnall Gleeson', 'Alicia Vikander', 'Oscar Isaac', 'Sonoya Mizuno', 'Corey Johnson'],
    posterColor: '#28336e',
    genre: 'Sci-Fi',
    releaseDate: '2015-04-10',
  },
  // A07 — selected by Buri 2026-08-08; TMDB 37724 scaffold, review-only
  {
    id: 'skyfall',
    title: 'Skyfall',
    year: 2012,
    director: ['Sam Mendes'],
    writers: ['John Logan', 'Neal Purvis', 'Robert Wade'],
    topCast: ['Daniel Craig', 'Judi Dench', 'Javier Bardem', 'Ralph Fiennes', 'Naomie Harris'],
    deepCast: ['Ben Whishaw'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '2012-11-09',
  },
  // A08 — selected by Buri 2026-08-08; TMDB 8467 scaffold, review-only
  {
    id: 'dumb-and-dumber',
    title: 'Dumb and Dumber',
    year: 1994,
    director: ['Peter Farrelly'],
    writers: ['Bobby Farrelly', 'Bennett Yellin', 'Peter Farrelly'],
    topCast: ['Jim Carrey', 'Jeff Daniels', 'Lauren Holly', 'Teri Garr', 'Charles Rocket'],
    posterColor: '#257068',
    genre: 'Comedy',
    releaseDate: '1994-12-16',
  },
  // A09 — selected by Buri 2026-08-08; TMDB 69 scaffold, review-only
  {
    id: 'walk-the-line',
    title: 'Walk the Line',
    year: 2005,
    director: ['James Mangold'],
    writers: ['Gill Dennis', 'James Mangold'],
    topCast: ['Joaquin Phoenix', 'Reese Witherspoon', 'Ginnifer Goodwin', 'Robert Patrick', 'Dallas Roberts'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '2005-11-18',
  },
  // A10 — selected by Buri 2026-08-08; TMDB 920 scaffold, review-only
  {
    id: 'cars',
    title: 'Cars',
    year: 2006,
    director: ['John Lasseter'],
    writers: ['Dan Fogelman', 'Joe Ranft', 'John Lasseter', 'Kiel Murray', 'Phil Lorin', 'Jørgen Klubien'],
    topCast: ['Owen Wilson', 'Paul Newman', 'Bonnie Hunt', 'Larry the Cable Guy', 'Cheech Marin'],
    deepCast: ['Tony Shalhoub', 'John Ratzenberger', 'Michael Keaton', 'Andrew Stanton', 'Lou Romano', 'Elissa Knight', 'Tom Hanks', 'Tim Allen'],
    posterColor: '#2d70b6',
    genre: 'Animation',
    releaseDate: '2006-06-09',
  },
  // A11 — selected by Buri 2026-08-08; TMDB 10528 scaffold, review-only
  {
    id: 'sherlock-holmes',
    title: 'Sherlock Holmes',
    year: 2009,
    director: ['Guy Ritchie'],
    writers: ['Anthony Peckham', 'Simon Kinberg', 'Michael Robert Johnson'],
    topCast: ['Robert Downey Jr.', 'Jude Law', 'Rachel McAdams', 'Mark Strong', 'Eddie Marsan'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '2009-12-25',
  },
  // A12 — selected by Buri 2026-08-08; TMDB 19995 scaffold, review-only
  {
    id: 'avatar',
    title: 'Avatar',
    year: 2009,
    director: ['James Cameron'],
    writers: ['James Cameron'],
    topCast: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver', 'Stephen Lang', 'Michelle Rodriguez'],
    deepCast: ['Giovanni Ribisi'],
    posterColor: '#28336e',
    genre: 'Sci-Fi',
    series: 'avatar',
    releaseDate: '2009-12-18',
  },
  // A13 — selected by Buri 2026-08-08; TMDB 747 scaffold, review-only
  {
    id: 'shaun-of-the-dead',
    title: 'Shaun of the Dead',
    year: 2004,
    director: ['Edgar Wright'],
    writers: ['Simon Pegg', 'Edgar Wright'],
    topCast: ['Simon Pegg', 'Nick Frost', 'Kate Ashfield', 'Lucy Davis', 'Dylan Moran'],
    deepCast: ['Martin Freeman'],
    posterColor: '#331025',
    genre: 'Horror',
    releaseDate: '2004-09-24',
  },
  // A14 — selected by Buri 2026-08-08; TMDB 693134 scaffold, review-only
  {
    id: 'dune-part-two',
    title: 'Dune: Part Two',
    year: 2024,
    director: ['Denis Villeneuve'],
    writers: ['Denis Villeneuve', 'Jon Spaihts'],
    topCast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem', 'Josh Brolin'],
    deepCast: ['Florence Pugh', 'Dave Bautista', 'Christopher Walken', 'Stellan Skarsgård', 'Charlotte Rampling'],
    posterColor: '#28336e',
    genre: 'Sci-Fi',
    series: 'dune',
    releaseDate: '2024-03-01',
  },
  // A15 — selected by Buri 2026-08-08; TMDB 1089 scaffold, review-only
  {
    id: 'point-break',
    title: 'Point Break',
    year: 1991,
    director: ['Kathryn Bigelow'],
    writers: ['W. Peter Iliff'],
    topCast: ['Keanu Reeves', 'Patrick Swayze', 'Lori Petty', 'Gary Busey', 'John C. McGinley'],
    deepCast: ['Tom Sizemore'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '1991-07-12',
  },
  // A16 — selected by Buri 2026-08-08; TMDB 925 scaffold, review-only
  {
    id: 'do-the-right-thing',
    title: 'Do the Right Thing',
    year: 1989,
    director: ['Spike Lee'],
    writers: ['Spike Lee'],
    topCast: ['Spike Lee', 'Danny Aiello', 'Ossie Davis', 'Ruby Dee', 'Giancarlo Esposito'],
    deepCast: ['Samuel L. Jackson', 'Frank Vincent'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '1989-06-30',
  },
  // B01 — selected by Buri 2026-08-08; TMDB 429197 scaffold, review-only
  {
    id: 'vice',
    title: 'Vice',
    year: 2018,
    director: ['Adam McKay'],
    writers: ['Adam McKay'],
    topCast: ['Christian Bale', 'Amy Adams', 'Steve Carell', 'Sam Rockwell', 'Alison Pill'],
    deepCast: ['Tyler Perry', 'Alfred Molina'],
    posterColor: '#257068',
    genre: 'Comedy',
    releaseDate: '2018-12-25',
  },
  // B02 — selected by Buri 2026-08-08; TMDB 68734 scaffold, review-only
  {
    id: 'argo',
    title: 'Argo',
    year: 2012,
    director: ['Ben Affleck'],
    writers: ['Chris Terrio'],
    topCast: ['Ben Affleck', 'Bryan Cranston', 'Alan Arkin', 'John Goodman', 'Victor Garber'],
    deepCast: ['Kyle Chandler', 'Bob Gunton'],
    posterColor: '#4a3960',
    genre: 'Thriller',
    releaseDate: '2012-10-12',
  },
  // B03 — selected by Buri 2026-08-08; TMDB 1824 scaffold, review-only
  {
    id: '50-first-dates',
    title: '50 First Dates',
    year: 2004,
    director: ['Peter Segal'],
    writers: ['George Wing'],
    topCast: ['Adam Sandler', 'Drew Barrymore', 'Rob Schneider', 'Sean Astin', 'Lusia Strus'],
    posterColor: '#a13d5d',
    genre: 'Romance',
    releaseDate: '2004-02-13',
  },
  // B04 — selected by Buri 2026-08-08; TMDB 650 scaffold, review-only
  {
    id: 'boyz-n-the-hood',
    title: 'Boyz n the Hood',
    year: 1991,
    director: ['John Singleton'],
    writers: ['John Singleton'],
    topCast: ['Cuba Gooding Jr.', 'Laurence Fishburne', 'Ice Cube', 'Morris Chestnut', 'Angela Bassett'],
    deepCast: ['Regina King'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '1991-07-12',
  },
  // B05 — selected by Buri 2026-08-08; TMDB 76 scaffold, review-only
  {
    id: 'before-sunrise',
    title: 'Before Sunrise',
    year: 1995,
    director: ['Richard Linklater'],
    writers: ['Kim Krizan', 'Richard Linklater'],
    topCast: ['Ethan Hawke', 'Julie Delpy', 'Andrea Eckert', 'Hanno Pöschl', 'Karl Bruckschwaiger'],
    deepCast: ['Adam Goldberg'],
    posterColor: '#a13d5d',
    genre: 'Romance',
    releaseDate: '1995-01-27',
  },
  // B06 — selected by Buri 2026-08-08; TMDB 1584 scaffold, review-only
  {
    id: 'school-of-rock',
    title: 'School of Rock',
    year: 2003,
    director: ['Richard Linklater'],
    writers: ['Mike White'],
    topCast: ['Jack Black', 'Joan Cusack', 'Mike White', 'Sarah Silverman', 'Miranda Cosgrove'],
    posterColor: '#257068',
    genre: 'Comedy',
    releaseDate: '2003-10-03',
  },
  // B07 — selected by Buri 2026-08-08; TMDB 1091 scaffold, review-only
  {
    id: 'the-thing',
    title: 'The Thing',
    year: 1982,
    director: ['John Carpenter'],
    writers: ['Bill Lancaster'],
    topCast: ['Kurt Russell', 'Wilford Brimley', 'T.K. Carter', 'David Clennon', 'Keith David'],
    posterColor: '#331025',
    genre: 'Horror',
    releaseDate: '1982-06-25',
  },
  // B08 — selected by Buri 2026-08-08; TMDB 49538 scaffold, review-only
  {
    id: 'x-men-first-class',
    title: 'X-Men: First Class',
    year: 2011,
    director: ['Matthew Vaughn'],
    writers: ['Zack Stentz', 'Matthew Vaughn', 'Jane Goldman', 'Ashley Miller'],
    topCast: ['James McAvoy', 'Michael Fassbender', 'Jennifer Lawrence', 'Rose Byrne', 'Kevin Bacon'],
    deepCast: ['Nicholas Hoult', 'Zoë Kravitz', 'Matt Craven', 'Hugh Jackman'],
    posterColor: '#26303c',
    genre: 'Action',
    series: 'x-men',
    releaseDate: '2011-06-03',
  },
  // B09 — selected by Buri 2026-08-08; TMDB 9675 scaffold, review-only
  {
    id: 'sideways',
    title: 'Sideways',
    year: 2004,
    director: ['Alexander Payne'],
    writers: ['Alexander Payne', 'Jim Taylor'],
    topCast: ['Paul Giamatti', 'Thomas Haden Church', 'Virginia Madsen', 'Sandra Oh', 'Marylouise Burke'],
    posterColor: '#257068',
    genre: 'Comedy',
    releaseDate: '2004-10-22',
  },
  // B10 — selected by Buri 2026-08-08; TMDB 674 scaffold, review-only
  {
    id: 'harry-potter-and-the-goblet-of-fire',
    title: 'Harry Potter and the Goblet of Fire',
    year: 2005,
    director: ['Mike Newell'],
    writers: ['Steve Kloves'],
    topCast: ['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson', 'Brendan Gleeson', 'Michael Gambon'],
    deepCast: ['Ralph Fiennes', 'Robbie Coltrane', 'Alan Rickman', 'Gary Oldman', 'Jason Isaacs', 'Maggie Smith'],
    posterColor: '#2a5a32',
    genre: 'Adventure',
    series: 'harry-potter',
    releaseDate: '2005-11-18',
  },
  // B11 — selected by Buri 2026-08-08; TMDB 1493 scaffold, review-only
  {
    id: 'miss-congeniality',
    title: 'Miss Congeniality',
    year: 2000,
    director: ['Donald Petrie'],
    writers: ['Marc Lawrence', 'Katie Ford', 'Caryn Lucas'],
    topCast: ['Sandra Bullock', 'Benjamin Bratt', 'Heather Burns', 'Michael Caine', 'Ernie Hudson'],
    posterColor: '#257068',
    genre: 'Comedy',
    releaseDate: '2000-12-22',
  },
  // B12 — selected by Buri 2026-08-08; TMDB 10860 scaffold, review-only
  {
    id: 'steel-magnolias',
    title: 'Steel Magnolias',
    year: 1989,
    director: ['Herbert Ross'],
    writers: ['Robert Harling'],
    topCast: ['Sally Field', 'Dolly Parton', 'Shirley MacLaine', 'Daryl Hannah', 'Olympia Dukakis'],
    deepCast: ['Julia Roberts', 'Tom Skerritt', 'Kevin J. O\'Connor'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '1989-11-15',
  },
  // C01 — selected by Buri 2026-08-08; TMDB 1883 scaffold, review-only
  {
    id: 'malcolm-x',
    title: 'Malcolm X',
    year: 1992,
    director: ['Spike Lee'],
    writers: ['Arnold Perl', 'Spike Lee'],
    topCast: ['Denzel Washington', 'Angela Bassett', 'Albert Hall', 'Al Freeman Jr.', 'Delroy Lindo'],
    deepCast: ['Spike Lee', 'William Fichtner', 'Christopher Plummer', 'Karen Allen', 'Peter Boyle'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '1992-11-18',
  },
  // C02 — selected by Buri 2026-08-08; TMDB 487558 scaffold, review-only
  {
    id: 'blackkklansman',
    title: 'BlacKkKlansman',
    year: 2018,
    director: ['Spike Lee'],
    writers: ['David Rabinowitz', 'Spike Lee', 'Charlie Wachtel', 'Kevin Willmott'],
    topCast: ['John David Washington', 'Adam Driver', 'Topher Grace', 'Laura Harrier', 'Alec Baldwin'],
    posterColor: '#7a1f1f',
    genre: 'Crime',
    releaseDate: '2018-08-10',
  },
  // C03 — selected by Buri 2026-08-08; TMDB 110415 scaffold, review-only
  {
    id: 'snowpiercer',
    title: 'Snowpiercer',
    year: 2014,
    director: ['Bong Joon-ho'],
    writers: ['Bong Joon-ho', 'Kelly Masterson'],
    topCast: ['Chris Evans', 'Song Kang-ho', 'Ed Harris', 'John Hurt', 'Tilda Swinton'],
    deepCast: ['Octavia Spencer'],
    posterColor: '#28336e',
    genre: 'Sci-Fi',
    releaseDate: '2014-06-27',
  },
  // C04 — selected by Buri 2026-08-08; TMDB 11423 scaffold, review-only
  {
    id: 'memories-of-murder',
    title: 'Memories of Murder',
    year: 2005,
    director: ['Bong Joon-ho'],
    writers: ['Bong Joon-ho', 'Shim Sung-bo'],
    topCast: ['Song Kang-ho', 'Kim Sang-kyung', 'Kim Roi-ha', 'Song Jae-ho', 'Byun Hee-bong'],
    posterColor: '#7a1f1f',
    genre: 'Crime',
    releaseDate: '2005-07-15',
  },
  // C05 — selected by Buri 2026-08-08; TMDB 696506 scaffold, review-only
  {
    id: 'mickey-17',
    title: 'Mickey 17',
    year: 2025,
    director: ['Bong Joon-ho'],
    writers: ['Bong Joon-ho'],
    topCast: ['Robert Pattinson', 'Naomi Ackie', 'Steven Yeun', 'Mark Ruffalo', 'Toni Collette'],
    posterColor: '#28336e',
    genre: 'Sci-Fi',
    releaseDate: '2025-03-07',
  },
  // C06 — selected by Buri 2026-08-08; TMDB 8392 scaffold, review-only
  {
    id: 'my-neighbor-totoro',
    title: 'My Neighbor Totoro',
    year: 1993,
    director: ['Hayao Miyazaki'],
    writers: ['Hayao Miyazaki'],
    topCast: ['Noriko Hidaka', 'Chika Sakamoto', 'Hitoshi Takagi', 'Shigesato Itoi', 'Sumi Shimamoto'],
    posterColor: '#2d70b6',
    genre: 'Animation',
    releaseDate: '1993-05-07',
  },
  // C07 — selected by Buri 2026-08-08; TMDB 128 scaffold, review-only
  {
    id: 'princess-mononoke',
    title: 'Princess Mononoke',
    year: 1999,
    director: ['Hayao Miyazaki'],
    writers: ['Hayao Miyazaki'],
    topCast: ['Yoji Matsuda', 'Yuriko Ishida', 'Yuko Tanaka', 'Kaoru Kobayashi', 'Masahiko Nishimura'],
    posterColor: '#2d70b6',
    genre: 'Animation',
    releaseDate: '1999-10-29',
  },
  // C08 — selected by Buri 2026-08-08; TMDB 4935 scaffold, review-only
  {
    id: 'howls-moving-castle',
    title: 'Howl\'s Moving Castle',
    year: 2005,
    director: ['Hayao Miyazaki'],
    writers: ['Hayao Miyazaki'],
    topCast: ['Chieko Baisho', 'Takuya Kimura', 'Akihiro Miwa', 'Tatsuya Gashuin', 'Ryunosuke Kamiki'],
    posterColor: '#2d70b6',
    genre: 'Animation',
    releaseDate: '2005-06-10',
  },
  // C09 — selected by Buri 2026-08-08; TMDB 49047 scaffold, review-only
  {
    id: 'gravity',
    title: 'Gravity',
    year: 2013,
    director: ['Alfonso Cuarón'],
    writers: ['Jonás Cuarón', 'Alfonso Cuarón'],
    topCast: ['Sandra Bullock', 'George Clooney', 'Ed Harris', 'Orto Ignatiussen', 'Phaldut Sharma'],
    posterColor: '#28336e',
    genre: 'Sci-Fi',
    releaseDate: '2013-10-04',
  },
  // C10 — selected by Buri 2026-08-08; TMDB 426426 scaffold, review-only
  {
    id: 'roma',
    title: 'Roma',
    year: 2018,
    director: ['Alfonso Cuarón'],
    writers: ['Alfonso Cuarón'],
    topCast: ['Yalitza Aparicio', 'Marina de Tavira', 'Diego Cortina Autrey', 'Carlos Peralta', 'Marco Graf'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '2018-11-21',
  },
  // C11 — selected by Buri 2026-08-08; TMDB 9693 scaffold, review-only
  {
    id: 'children-of-men',
    title: 'Children of Men',
    year: 2006,
    director: ['Alfonso Cuarón'],
    writers: ['Timothy J. Sexton', 'David Arata', 'Alfonso Cuarón', 'Mark Fergus', 'Hawk Ostby'],
    topCast: ['Clive Owen', 'Clare-Hope Ashitey', 'Chiwetel Ejiofor', 'Julianne Moore', 'Michael Caine'],
    posterColor: '#28336e',
    genre: 'Sci-Fi',
    releaseDate: '2006-12-25',
  },
  // C12 — selected by Buri 2026-08-08; TMDB 673 scaffold, review-only
  {
    id: 'harry-potter-and-the-prisoner-of-azkaban',
    title: 'Harry Potter and the Prisoner of Azkaban',
    year: 2004,
    director: ['Alfonso Cuarón'],
    writers: ['Steve Kloves'],
    topCast: ['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson', 'Robbie Coltrane', 'Michael Gambon'],
    deepCast: ['Gary Oldman', 'Alan Rickman', 'Maggie Smith'],
    posterColor: '#2a5a32',
    genre: 'Adventure',
    series: 'harry-potter',
    releaseDate: '2004-06-04',
  },
  // C13 — selected by Buri 2026-08-08; TMDB 1103 scaffold, review-only
  {
    id: 'escape-from-new-york',
    title: 'Escape from New York',
    year: 1981,
    director: ['John Carpenter'],
    writers: ['John Carpenter', 'Nick Castle'],
    topCast: ['Kurt Russell', 'Lee Van Cleef', 'Ernest Borgnine', 'Donald Pleasence', 'Isaac Hayes'],
    deepCast: ['Harry Dean Stanton', 'Jamie Lee Curtis'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '1981-06-26',
  },
  // C14 — selected by Buri 2026-08-08; TMDB 8337 scaffold, review-only
  {
    id: 'they-live',
    title: 'They Live',
    year: 1988,
    director: ['John Carpenter'],
    writers: ['John Carpenter'],
    topCast: ['Roddy Piper', 'Keith David', 'Meg Foster', 'George Buck Flower', 'Peter Jason'],
    posterColor: '#28336e',
    genre: 'Sci-Fi',
    releaseDate: '1988-11-04',
  },
  // C15 — selected by Buri 2026-08-08; TMDB 948 scaffold, review-only
  {
    id: 'halloween',
    title: 'Halloween',
    year: 1978,
    director: ['John Carpenter'],
    writers: ['Debra Hill', 'John Carpenter'],
    topCast: ['Donald Pleasence', 'Jamie Lee Curtis', 'Nancy Kyes', 'P. J. Soles', 'Charles Cyphers'],
    posterColor: '#331025',
    genre: 'Horror',
    releaseDate: '1978-10-25',
  },
  // C16 — selected by Buri 2026-08-08; TMDB 9489 scaffold, review-only
  {
    id: 'youve-got-mail',
    title: 'You\'ve Got Mail',
    year: 1998,
    director: ['Nora Ephron'],
    writers: ['Nora Ephron', 'Delia Ephron'],
    topCast: ['Meg Ryan', 'Tom Hanks', 'Greg Kinnear', 'Parker Posey', 'Heather Burns'],
    deepCast: ['Steve Zahn'],
    posterColor: '#a13d5d',
    genre: 'Romance',
    releaseDate: '1998-12-18',
  },
  // C17 — selected by Buri 2026-08-08; TMDB 24803 scaffold, review-only
  {
    id: 'julie-and-julia',
    title: 'Julie & Julia',
    year: 2009,
    director: ['Nora Ephron'],
    writers: ['Nora Ephron'],
    topCast: ['Meryl Streep', 'Amy Adams', 'Stanley Tucci', 'Chris Messina', 'Linda Emond'],
    deepCast: ['Mary Kay Place'],
    posterColor: '#257068',
    genre: 'Comedy',
    releaseDate: '2009-08-07',
  },
  // E01 — selected by Buri 2026-08-08; TMDB 391713 scaffold, review-only
  {
    id: 'lady-bird',
    title: 'Lady Bird',
    year: 2017,
    director: ['Greta Gerwig'],
    writers: ['Greta Gerwig'],
    topCast: ['Saoirse Ronan', 'Laurie Metcalf', 'Tracy Letts', 'Lucas Hedges', 'Timothée Chalamet'],
    posterColor: '#257068',
    genre: 'Comedy',
    releaseDate: '2017-11-03',
  },
  // E02 — selected by Buri 2026-08-08; TMDB 331482 scaffold, review-only
  {
    id: 'little-women',
    title: 'Little Women',
    year: 2019,
    director: ['Greta Gerwig'],
    writers: ['Greta Gerwig'],
    topCast: ['Saoirse Ronan', 'Emma Watson', 'Florence Pugh', 'Eliza Scanlen', 'Laura Dern'],
    deepCast: ['Timothée Chalamet', 'Chris Cooper', 'Meryl Streep'],
    posterColor: '#a13d5d',
    genre: 'Romance',
    releaseDate: '2019-12-25',
  },
  // E03 — selected by Buri 2026-08-08; TMDB 153 scaffold, review-only
  {
    id: 'lost-in-translation',
    title: 'Lost in Translation',
    year: 2003,
    director: ['Sofia Coppola'],
    writers: ['Sofia Coppola'],
    topCast: ['Bill Murray', 'Scarlett Johansson', 'Giovanni Ribisi', 'Anna Faris', 'Akiko Takeshita'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '2003-09-18',
  },
  // E04 — selected by Buri 2026-08-08; TMDB 273895 scaffold, review-only
  {
    id: 'selma',
    title: 'Selma',
    year: 2014,
    director: ['Ava DuVernay'],
    writers: ['Paul Webb'],
    topCast: ['David Oyelowo', 'Carmen Ejogo', 'Tom Wilkinson', 'Giovanni Ribisi', 'Tim Roth'],
    deepCast: ['LaKeith Stanfield', 'Cuba Gooding Jr.', 'Martin Sheen'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '2014-12-25',
  },
  // E05 — selected by Buri 2026-08-08; TMDB 565310 scaffold, review-only
  {
    id: 'the-farewell',
    title: 'The Farewell',
    year: 2019,
    director: ['Lulu Wang'],
    writers: ['Lulu Wang'],
    topCast: ['Awkwafina', 'Zhao Shuzhen', 'Hong Lu', 'Hong Lin', 'Tzi Ma'],
    posterColor: '#257068',
    genre: 'Comedy',
    releaseDate: '2019-07-12',
  },
  // E06 — selected by Buri 2026-08-08; TMDB 666277 scaffold, review-only
  {
    id: 'past-lives',
    title: 'Past Lives',
    year: 2023,
    director: ['Celine Song'],
    writers: ['Celine Song'],
    topCast: ['Greta Lee', 'Teo Yoo', 'John Magaro', 'Moon Seung-ah', 'Leem Seung-min'],
    posterColor: '#a13d5d',
    genre: 'Romance',
    releaseDate: '2023-06-02',
  },
  // E07 — selected by Buri 2026-08-08; TMDB 531428 scaffold, review-only
  {
    id: 'portrait-of-a-lady-on-fire',
    title: 'Portrait of a Lady on Fire',
    year: 2019,
    director: ['Céline Sciamma'],
    writers: ['Céline Sciamma'],
    topCast: ['Noémie Merlant', 'Adèle Haenel', 'Luàna Bajrami', 'Valeria Golino', 'Christel Baras'],
    posterColor: '#a13d5d',
    genre: 'Romance',
    releaseDate: '2019-12-06',
  },
  // E08 — selected by Buri 2026-08-08; TMDB 194 scaffold, review-only
  {
    id: 'amelie',
    title: 'Amélie',
    year: 2001,
    director: ['Jean-Pierre Jeunet'],
    writers: ['Guillaume Laurant', 'Jean-Pierre Jeunet'],
    topCast: ['Audrey Tautou', 'Mathieu Kassovitz', 'Rufus', 'Serge Merlin', 'Jamel Debbouze'],
    posterColor: '#a13d5d',
    genre: 'Romance',
    releaseDate: '2001-11-16',
  },
  // E09 — selected by Buri 2026-08-08; TMDB 670 scaffold, review-only
  {
    id: 'oldboy',
    title: 'Oldboy',
    year: 2005,
    director: ['Park Chan-wook'],
    writers: ['Lim Joon-hyung', 'Hwang Jo-yoon', 'Park Chan-wook'],
    topCast: ['Choi Min-sik', 'Yoo Ji-tae', 'Kang Hye-jung', 'Kim Byeong-ok', 'Ji Dae-han'],
    posterColor: '#4a3960',
    genre: 'Thriller',
    releaseDate: '2005-03-25',
  },
  // E10 — selected by Buri 2026-08-08; TMDB 940721 scaffold, review-only
  {
    id: 'godzilla-minus-one',
    title: 'Godzilla Minus One',
    year: 2023,
    director: ['Takashi Yamazaki'],
    writers: ['Takashi Yamazaki'],
    topCast: ['Ryunosuke Kamiki', 'Minami Hamabe', 'Yuki Yamada', 'Munetaka Aoki', 'Hidetaka Yoshioka'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '2023-12-01',
  },
  // E11 — selected by Buri 2026-08-08; TMDB 579974 scaffold, review-only
  {
    id: 'rrr',
    title: 'RRR',
    year: 2022,
    director: ['S. S. Rajamouli'],
    writers: ['S. S. Rajamouli'],
    topCast: ['N.T. Rama Rao Jr.', 'Ram Charan', 'Olivia Morris', 'Ray Stevenson', 'Alison Doody'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '2022-03-25',
  },
  // E12 — selected by Buri 2026-08-08; TMDB 14736 scaffold, review-only
  {
    id: 'love-and-basketball',
    title: 'Love & Basketball',
    year: 2000,
    director: ['Gina Prince-Bythewood'],
    writers: ['Gina Prince-Bythewood'],
    topCast: ['Sanaa Lathan', 'Omar Epps', 'Chris Warren', 'Kyla Pratt', 'Alfre Woodard'],
    posterColor: '#a13d5d',
    genre: 'Romance',
    releaseDate: '2000-04-21',
  },
  // F01 — selected by Buri 2026-08-08; TMDB 402431 scaffold, review-only
  {
    id: 'wicked',
    title: 'Wicked',
    year: 2024,
    director: ['Jon M. Chu'],
    writers: ['Winnie Holzman', 'Dana Fox'],
    topCast: ['Cynthia Erivo', 'Ariana Grande', 'Michelle Yeoh', 'Jonathan Bailey', 'Ethan Slater'],
    deepCast: ['Jeff Goldblum', 'Peter Dinklage'],
    posterColor: '#2a5a32',
    genre: 'Adventure',
    series: 'wicked',
    releaseDate: '2024-11-22',
  },
  // F02 — selected by Buri 2026-08-08; TMDB 1233413 scaffold, review-only
  {
    id: 'sinners',
    title: 'Sinners',
    year: 2025,
    director: ['Ryan Coogler'],
    writers: ['Ryan Coogler'],
    topCast: ['Michael B. Jordan', 'Hailee Steinfeld', 'Miles Caton', 'Jack O\'Connell', 'Wunmi Mosaku'],
    posterColor: '#331025',
    genre: 'Horror',
    releaseDate: '2025-04-18',
  },
  // F03 — selected by Buri 2026-08-08; TMDB 1054867 scaffold, review-only
  {
    id: 'one-battle-after-another',
    title: 'One Battle After Another',
    year: 2025,
    director: ['Paul Thomas Anderson'],
    writers: ['Paul Thomas Anderson'],
    topCast: ['Leonardo DiCaprio', 'Sean Penn', 'Chase Infiniti', 'Benicio del Toro', 'Regina Hall'],
    deepCast: ['Wood Harris', 'Jena Malone'],
    posterColor: '#4a3960',
    genre: 'Thriller',
    releaseDate: '2025-09-26',
  },
  // F04 — selected by Buri 2026-08-08; TMDB 911430 scaffold, review-only
  {
    id: 'f1',
    title: 'F1',
    year: 2025,
    director: ['Joseph Kosinski'],
    writers: ['Ehren Kruger'],
    topCast: ['Brad Pitt', 'Damson Idris', 'Javier Bardem', 'Kerry Condon', 'Tobias Menzies'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '2025-06-27',
  },
  // F05 — selected by Buri 2026-08-08; TMDB 1061474 scaffold, review-only
  {
    id: 'superman-2025',
    title: 'Superman (David Corenswet)',
    year: 2025,
    director: ['James Gunn'],
    writers: ['James Gunn'],
    topCast: ['David Corenswet', 'Rachel Brosnahan', 'Nicholas Hoult', 'Edi Gathegi', 'Nathan Fillion'],
    deepCast: ['Bradley Cooper'],
    posterColor: '#26303c',
    genre: 'Action',
    releaseDate: '2025-07-11',
  },
  // F06 — selected by Buri 2026-08-08; TMDB 803796 scaffold, review-only
  {
    id: 'kpop-demon-hunters',
    title: 'KPop Demon Hunters',
    year: 2025,
    director: ['Chris Appelhans', 'Maggie Kang'],
    writers: ['Maggie Kang', 'Danya Jimenez', 'Hannah McMechan', 'Chris Appelhans'],
    topCast: ['Arden Cho', 'May Hong', 'Ji-young Yoo', 'Ahn Hyo-seop', 'Yunjin Kim'],
    posterColor: '#2d70b6',
    genre: 'Animation',
  },
  // F07 — selected by Buri 2026-08-08; TMDB 969681 scaffold, review-only
  {
    id: 'spider-man-brand-new-day',
    title: 'Spider-Man: Brand New Day',
    year: 2026,
    director: ['Destin Daniel Cretton'],
    writers: ['Erik Sommers', 'Chris McKenna'],
    topCast: ['Tom Holland', 'Sadie Sink', 'Tramell Tillman', 'Zendaya', 'Jon Bernthal'],
    deepCast: ['Mark Ruffalo', 'Florence Pugh', 'Marisa Tomei', 'Naomi Watts'],
    posterColor: '#26303c',
    genre: 'Action',
    series: 'spider-man-holland',
    releaseDate: '2026-07-31',
  },
  // F08 — selected by Buri 2026-08-08; TMDB 1226863 scaffold, review-only
  {
    id: 'the-super-mario-galaxy-movie',
    title: 'The Super Mario Galaxy Movie',
    year: 2026,
    director: ['Michael Jelenic', 'Aaron Horvath'],
    writers: ['Matthew Fogel'],
    topCast: ['Chris Pratt', 'Charlie Day', 'Anya Taylor-Joy', 'Jack Black', 'Keegan-Michael Key'],
    deepCast: ['Donald Glover', 'Issa Rae'],
    posterColor: '#2d70b6',
    genre: 'Animation',
    series: 'super-mario',
    releaseDate: '2026-04-01',
  },
  // F09 — selected by Buri 2026-08-08; TMDB 1317288 scaffold, review-only
  {
    id: 'marty-supreme',
    title: 'Marty Supreme',
    year: 2025,
    director: ['Josh Safdie'],
    writers: ['Ronald Bronstein', 'Josh Safdie'],
    topCast: ['Timothée Chalamet', 'Gwyneth Paltrow', 'Odessa A\'zion', 'Kevin O\'Leary', 'Tyler, The Creator'],
    deepCast: ['David Mamet'],
    posterColor: '#6b4a23',
    genre: 'Drama',
    releaseDate: '2025-12-19',
  },
  // F10 — selected by Buri 2026-08-08; TMDB 1062722 scaffold, review-only
  {
    id: 'frankenstein-2025',
    title: 'Frankenstein (2025)',
    year: 2025,
    director: ['Guillermo del Toro'],
    writers: ['Guillermo del Toro'],
    topCast: ['Oscar Isaac', 'Jacob Elordi', 'Christoph Waltz', 'Mia Goth', 'Felix Kammerer'],
    posterColor: '#331025',
    genre: 'Horror',
    releaseDate: '2025-10-17',
  },
]
